### ISSUE TITLE
Switch network warning remains after wallet has switched

### ISSUE THREAD

**Issue by edr4l** [centfinance/Cent.Dex_ExchangeUI#54]
The Switch network warning remains after wallet has switched to be aligned with network user is currently on in Symmetric 
User needs to hit Celo again inn leftnav for page to acknowledge switch.

Steps to reproduce:

- Be on Celo in Symmetric and xDai in metamask (and therefore seeing wrong network warning)
- Opt to switch network in Symmetric
- Confirm switch to celo in MetaMask
- We are switched, but user still sees !Wrong network

When user hits Celo in leftnav the wrong network and switch buttons disappear, but these should probably do so automatically

https://user-images.githubusercontent.com/94110907/141283483-ead1add9-1738-4061-9ecc-c84cafc77b05.mp4

**Comment by tqmvt** [comment]
Fixed by [PR 170](https://github.com/centfinance/Symmetric.PoolsUI/pull/170)
