### ISSUE TITLE
Go through project including submodules to check that log4j if used is at version 2.16.0

### ISSUE THREAD

**Issue by TheNewAutonomy** [centfinance/Cent.Dex_ExchangeUI#66]
This is critical and needs to be done as early as possible.

https://www.ncsc.gov.uk/information/log4j-vulnerability-what-everyone-needs-to-know

**Comment by tqmvt** [comment]
log4js@^0.6.31 was used for packages:

- browserify-zlib
- diff
- vue-infinite-scroll

So it's fine @TheNewAutonomy
